---
title: "git_01"
author: "Simone Delos Santos"
date: "23 Feb 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A boat beneath a sunny sky  
Lingering onward dreamily  
In an evening of July--  
 Children three that nestle near,  
Eager eye and willing ear,   

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,  
Some say in ice.  
From what I've tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."   

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
When deeds splay before us  precious as gold & unused chances  
stripped from the whine-bone, we know the moment kindheartedness  
walks in. Each praise be echoes us back as the years uncount  
themselves, eating salt. Though blood first shaped us on the climbing wheel,  
the human mind lit by the savanna’s ice star & thistle rose,  
your knowing gaze enters a room & opens the day,  
saying we were made for fun. Even the bedazzled brute know  
when sunlight falls through leaves across honed knives on the table.    
If we can see it push shadows  aside, growing closer, are we less    
broken? A barometer, temperature  gauge, a ruler in minus fractions  
& pedigrees, a thingmajig,  a probe with an all-seeing eye,  
what do we need to measurekindness, every unheld breath,    
every unkind leapyear?Sometimes a sober voice is enough    
to calm the waters & drive away  the false witnesses, saying,  
Look, here are the broken treaties Beauty  brought to us earthbound sentinels.  
